{% set name = "argh" %}
{% set version = "0.30.2" %}
{% set hash = "25b2bca3a6770ee41d76c4a32825b737412adddc7f850a6c77bc8a4f37122dcb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3
  run:
    - python >=3

test:
  imports:
    - argh

about:
  home: https://github.com/neithere/argh
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: The Natural CLI.
  description: |
    An argparse wrapper that doesn't make you say "argh" each time you deal with it.
  doc_url: http://argh.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - daler
    - goanpeca
    - tschoonj
