{% set name = "argh" %}
{% set version = "0.27.1" %}
{% set hash = "db06d91081f1724e347ccdb789c9570fec94737e755af1598837293e01fc4cd2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - python >=3

test:
  imports:
    - argh

about:
  home: https://github.com/neithere/argh
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: The Natural CLI.
  description: |
    An argparse wrapper that doesn't make you say "argh" each time you deal with it.
  doc_url: http://argh.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - goanpeca
    - daler
    - tschoonj
